#!/bin/sh
set -e
PKG=pulseaudio-novena
if [ "$1" = configure ] ; then
	dpkg-divert --add --package ${PKG} --rename \
		--divert /etc/pulse/default.pa.distrib /etc/pulse/default.pa
	[ \! -e /etc/pulse/default.pa -o -L /etc/pulse/default.pa ] \
		&& ln -sf /etc/pulse/novena.pa /etc/pulse/default.pa
fi
#DEBHELPER#
exit 0
